### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'build'

### ISSUE THREAD

**Issue by mm04926412** [pytorch/nestedtensor#289]
I followed the instructions on the github page and the build script failed. I am unsure why. I've tried git cloning several times. I am using a conda environment.

**Comment by cpuhrsch** [comment]
Hello @mm04926412,

Thank you for your interest! Could I kindly ask you to post the full log of the commands you ran and the output so I can help you further?

Thanks,
Christian

**Comment by mm04926412** [comment]
Sure, I provide the output below

+ pushd third_party/pytorch
~/Dropbox/Projects/project/nestedtensor/third_party/pytorch ~/Dropbox/Projects/project/nestedtensor
+ python setup.py clean
Building wheel torch-1.7.0a0
running clean
+ python setup.py develop
Building wheel torch-1.7.0a0
-- Building version 1.7.0a0
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/user/Dropbox/Projects/project/nestedtensor/third_party/pytorch/torch -DCMAKE_PREFIX_PATH=/home/user/anaconda3/envs/pytorch-cuda-11/lib/python3.8/site-packages -DNUMPY_INCLUDE_DIR=/home/user/anaconda3/envs/pytorch-cuda-11/lib/python3.8/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/user/anaconda3/envs/pytorch-cuda-11/bin/python -DPYTHON_INCLUDE_DIR=/home/user/anaconda3/envs/pytorch-cuda-11/include/python3.8 -DPYTHON_LIBRARY=/home/user/anaconda3/envs/pytorch-cuda-11/lib/libpython3.8.so.1.0 -DTORCH_BUILD_VERSION=1.7.0a0 -DUSE_NUMPY=True /home/user/Dropbox/Projects/project/nestedtensor/third_party/pytorch
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    build_deps()
  File "setup.py", line 308, in build_deps
    build_caffe2(version=version,
  File "/home/user/Dropbox/Projects/project/nestedtensor/third_party/pytorch/tools/build_pytorch_libs.py", line 54, in build_caffe2
    cmake.generate(version,
  File "/home/user/Dropbox/Projects/project/nestedtensor/third_party/pytorch/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/home/user/Dropbox/Projects/project/nestedtensor/third_party/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/user/anaconda3/envs/pytorch-cuda-11/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/user/anaconda3/envs/pytorch-cuda-11/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/user/anaconda3/envs/pytorch-cuda-11/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/anaconda3/envs/pytorch-cuda-11/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'build'

**Comment by mm04926412** [comment]
I hope that's helpful! I find padding functionality in pytorch to be the least intuitive part of it and this solution seems excellent!

**Comment by cpuhrsch** [comment]
Hm, could you try creating the build directory and then run it again?
```
mkdir /home/user/Dropbox/Projects/project/nestedtensor/third_party/pytorch/build
```

Otherwise, here is a link to some "preview" binaries. We'll have a better formatted link up soon with frequent builds (these are based on a fairly recent commit, but not the latest).

```
pip install https://3388-217161669-gh.circle-artifacts.com/0/wheels/torch-1.7.0a0-cp36-cp36m-linux_x86_64.whl
pip install https://3388-217161669-gh.circle-artifacts.com/0/wheels/nestedtensor-0.0.1.dev20201173-cp36-cp36m-linux_x86_64.whl
```

These binaries support CPU only and work on linux. CUDA binaries will be available within the next weeks.

**Comment by mm04926412** [comment]
It turns out this wasn't caused by anything in the script and was a simple permission error with mkdir! My apologies! To clarify before closing this is this library ready to be used? I was installing it with hope to apply it to my NLP model with vast differences in sentence length.

**Comment by cpuhrsch** [comment]
This feature is designated [prototype](https://pytorch.org/blog/pytorch-feature-classification-changes/). To copy paste the relevant section from the link:
"""
Previously these were features that were known about by developers who paid close attention to RFCs and to features that land in master. In this case the feature is not available as part of binary distributions like PyPI or Conda (except maybe behind run-time flags), but we would like to get high bandwidth partner feedback ahead of a real release in order to gauge utility and any changes we need to make to the UX. To test these kinds of features we would, depending on the feature, recommend building from master or using the nightly whls that are made available on pytorch.org. For each prototype feature, a pointer to draft docs or other instructions will be provided.

Level of commitment: We are committing to gathering high bandwidth feedback only. Based on this feedback and potential further engagement between community members, we as a community will decide if we want to upgrade the level of commitment or to fail fast. Additionally, while some of these features might be more speculative (e.g. new Frontend APIs), others have obvious utility (e.g. model optimization) but may be in a state where gathering feedback outside of high bandwidth channels is not practical, e.g. the feature may be in an earlier state, may be moving fast (PRs are landing too quickly to catch a major release) and/or generally active development is underway.
"""
